# Generated by Django 2.2.7 on 2019-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(protocol='ipv4')),
                ('ipv6', models.GenericIPAddressField(protocol='ipv6')),
                ('both', models.GenericIPAddressField()),
            ],
        ),
    ]
